version: '3.5'
services:
  api:
    env_file:
      - .env.production
    container_name: api
    build:
      context: ./
    restart: always
    ports: 
      - 8080:8080
    networks:
      - db-net
    depends_on:
      - db

  db:
    env_file:
      - .env.production
    image: mysql
    container_name: database-layer
    restart: always
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      - db-net
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
        - ./scripts/pro.sql:/docker-entrypoint-initdb.d/1.sql
networks: 
  db-net:
    

  